---
# tasks file for python_env
#
#
 - name: add user
      user:
        name: indico
        group: nginx
        home: /opt/indico
        shell: /bin/bash
        system: true
        create_home: true
    
  
      
    - name: curl pyenv
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash

    - name: bashrc cat
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: |
        cat >> ~/.bashrc <<'EOF'
        export PATH="/opt/indico/.pyenv/bin:/usr/pgsql-13/bin:/opt/indico/.venv/bin:$PATH"
        eval "$(pyenv init --path)"
        eval "$(pyenv init -)"
      
   

    - name: source bashrc
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: source ~/.bashrc

    
    - name: pyenv install
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: . ~/.bashrc &&  pyenv install 3.9.16

    - name: pyenv global
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: . ~/.bashrc && pyenv global 3.9.16

    - name: python m
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: . ~/.bashrc && python -m venv --upgrade-deps --prompt indico ~/.venv

    - name: source activate
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: . ~/.bashrc && source ~/.venv/bin/activate

    - name: export path
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin"
      shell: . ~/.bashrc && export PATH="$PATH:/usr/pgsql-13/bin"

    - name: echo and append
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin:/usr/pgsql-13/bin"
      shell: . ~/.bashrc && echo 'source ~/.venv/bin/activate' >> ~/.bashrc


    - name: pip install wheel
      become: yes
      become_user: indico
      become_method: su
      environment:
       path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin:/usr/pgsql-13/bin/"
      shell: . ~/.bashrc && pip install wheel


    - name: pip install uwsgi
      become: yes
      become_user: indico
      become_method: su
      environment:
       path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin:/usr/pgsql-13/bin/"
      shell: . ~/.bashrc && pip install uwsgi

    - name: pip install indico
      become: yes
      become_user: indico
      become_method: su
      environment:
       path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin:/usr/pgsql-13/bin/"
      shell: . ~/.bashrc && pip install indico
  
    - name: pip install root
      yum:
        name: python-pip
    
    - name: pip pexpect
      pip:
        name: pexpect

    - name: indico setup wizard
      become: yes
      become_user: indico
      become_method: su
      environment:
        path: "/opt/indico/.pyenv/shims:/opt/indico/.pyenv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/indico/.local/bin:/opt/indico/bin:/usr/pgsql-13/bin"
      expect:
        command: /bin/bash -c "source ~/.bashrc && export PROMPT_TOOLKIT_COLOR_DEPTH=DEPTH_1_BIT && indico setup wizard | sed 's/\x1b\[0m//g'"
        responses:
          Indico root path:
            - ""
            - "\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bhttps://192.168.56.102"
          PostgreSQL database URI:
            - ""
            - ""
          Redis URI \(cache\):
            - ""
            - "email@email.com"
          Admin email:
            - ""
            - ""
          SMTP host:
            - ""
            - ""
          SMTP username:
            - ""
            - ""
          Default timezone:
            - ""
            - "y"
          Enable system notices\?:
            - "y"
            - "y"

        echo: yes
        timeout: 10
